-- DELETE FROM message_to_user;
-- DELETE FROM unsend_message_from_user;
-- DELETE FROM friend_relation;
-- DELETE FROM friend_request;
-- DELETE FROM group_request;
-- DELETE FROM basic_group_data;

-- select * FROM message_to_user; 
-- select * from user_status;
-- select * from basic_group_data;
-- select * from friend_relation;
-- select * from friend_request;
-- select * from group_request;